// https://api.swu-db.com/cards/search?q=+type%3ABase
// last update 3/30/2024

export const OFFLINE_BASES = {
  total_cards: 12,
  data: [
    {
      Set: "SOR",
      Number: "029",
      Name: "Administrator's Tower",
      Subtitle: "Cloud City",
      Type: "Base",
      Aspects: ["Cunning"],
      HP: "30",
      DoubleSided: false,
      Rarity: "Common",
      Unique: false,
      Artist: "Tyler Edlin",
      FrontArt:
        "https://d3alac64utt23z.cloudfront.net/images/cards/SOR/029.png",
      VariantType: "Normal",
      MarketPrice: "0.07",
    },
    {
      Set: "SOR",
      Number: "020",
      Name: "Capital City",
      Subtitle: "Lothal",
      Type: "Base",
      Aspects: ["Vigilance"],
      HP: "30",
      DoubleSided: false,
      Rarity: "Common",
      Unique: false,
      Artist: "Sebastian Guidobono",
      FrontArt:
        "https://d3alac64utt23z.cloudfront.net/images/cards/SOR/020.png",
      VariantType: "Normal",
      MarketPrice: "0.10",
    },
    {
      Set: "SOR",
      Number: "026",
      Name: "Catacombs of Cadera",
      Subtitle: "Jedha",
      Type: "Base",
      Aspects: ["Aggression"],
      HP: "30",
      DoubleSided: false,
      Rarity: "Common",
      Unique: false,
      Artist: "Tyler Edlin",
      FrontArt:
        "https://d3alac64utt23z.cloudfront.net/images/cards/SOR/026.png",
      VariantType: "Normal",
      MarketPrice: "0.16",
    },
    {
      Set: "SOR",
      Number: "030",
      Name: "Chopper Base",
      Subtitle: "Atollon",
      Type: "Base",
      Aspects: ["Cunning"],
      HP: "30",
      DoubleSided: false,
      Rarity: "Common",
      Unique: false,
      Artist: "Tyler Edlin",
      FrontArt:
        "https://d3alac64utt23z.cloudfront.net/images/cards/SOR/030.png",
      VariantType: "Normal",
      MarketPrice: "0.10",
    },
    {
      Set: "SOR",
      Number: "023",
      Name: "Command Center",
      Subtitle: "Death Star",
      Type: "Base",
      Aspects: ["Command"],
      HP: "30",
      DoubleSided: false,
      Rarity: "Common",
      Unique: false,
      Artist: "Stephen Zavala",
      FrontArt:
        "https://d3alac64utt23z.cloudfront.net/images/cards/SOR/023.png",
      VariantType: "Normal",
      MarketPrice: "0.07",
    },
    {
      Set: "SOR",
      Number: "021",
      Name: "Dagobah Swamp",
      Subtitle: "Dagobah",
      Type: "Base",
      Aspects: ["Vigilance"],
      HP: "30",
      DoubleSided: false,
      Rarity: "Common",
      Unique: false,
      Artist: "Tyler Edlin",
      FrontArt:
        "https://d3alac64utt23z.cloudfront.net/images/cards/SOR/021.png",
      VariantType: "Normal",
      MarketPrice: "0.11",
    },
    {
      Set: "SOR",
      Number: "024",
      Name: "Echo Base",
      Subtitle: "Hoth",
      Type: "Base",
      Aspects: ["Command"],
      HP: "30",
      DoubleSided: false,
      Rarity: "Common",
      Unique: false,
      Artist: "Stephen Zavala",
      FrontArt:
        "https://d3alac64utt23z.cloudfront.net/images/cards/SOR/024.png",
      VariantType: "Normal",
      MarketPrice: "0.10",
    },
    {
      Set: "SOR",
      Number: "022",
      Name: "Energy Conversion Lab",
      Subtitle: "Eadu",
      Type: "Base",
      Aspects: ["Command"],
      HP: "25",
      FrontText:
        "Epic Action: Play a unit that costs 6 or less from your hand. Give it AMBUSH for this phase.",
      DoubleSided: false,
      Rarity: "Rare",
      Unique: false,
      Keywords: ["Ambush"],
      Artist: "Adrien Girod",
      FrontArt:
        "https://d3alac64utt23z.cloudfront.net/images/cards/SOR/022.png",
      VariantType: "Normal",
      MarketPrice: "2.87",
    },
    {
      Set: "SOR",
      Number: "028",
      Name: "Jedha City",
      Subtitle: "Jedha",
      Type: "Base",
      Aspects: ["Cunning"],
      HP: "25",
      FrontText: "Epic Action: Give a non-leader unit -4/-0 for this phase.",
      DoubleSided: false,
      Rarity: "Rare",
      Unique: false,
      Artist: "Roc\u00edo Esp\u00edn",
      FrontArt:
        "https://d3alac64utt23z.cloudfront.net/images/cards/SOR/028.png",
      VariantType: "Normal",
      MarketPrice: "0.31",
    },
    {
      Set: "SOR",
      Number: "027",
      Name: "Kestro City",
      Subtitle: "Vardos",
      Type: "Base",
      Aspects: ["Aggression"],
      HP: "30",
      DoubleSided: false,
      Rarity: "Common",
      Unique: false,
      Artist: "Stephen Zavala",
      FrontArt:
        "https://d3alac64utt23z.cloudfront.net/images/cards/SOR/027.png",
      VariantType: "Normal",
      MarketPrice: "0.08",
    },
    {
      Set: "SOR",
      Number: "019",
      Name: "Security Complex",
      Subtitle: "Scarif",
      Type: "Base",
      Aspects: ["Vigilance"],
      HP: "25",
      FrontText: "Epic Action: Give a Shield token to a non-leader unit.",
      DoubleSided: false,
      Rarity: "Rare",
      Unique: false,
      Artist: "Tyler Edlin",
      FrontArt:
        "https://d3alac64utt23z.cloudfront.net/images/cards/SOR/019.png",
      VariantType: "Normal",
      MarketPrice: "0.24",
    },
    {
      Set: "SOR",
      Number: "025",
      Name: "Tarkintown",
      Subtitle: "Lothal",
      Type: "Base",
      Aspects: ["Aggression"],
      HP: "25",
      FrontText: "Epic Action: Deal 3 damage to a damaged non-leader unit.",
      DoubleSided: false,
      Rarity: "Rare",
      Unique: false,
      Artist: "Adrien Girod",
      FrontArt:
        "https://d3alac64utt23z.cloudfront.net/images/cards/SOR/025.png",
      VariantType: "Normal",
      MarketPrice: "0.24",
    },
  ],
};
